### ISSUE TITLE
setting scenario from command line overrides other options

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#88] opened 2021-04-07 12:02 UTC
since there is no scenario randomizer yet, i'm trying to write a shell script that would do it. i'm having issue setting VP (and probably other options that selected scenario would set). what i've tried (wonders scenario is just an example):

1/ setting -o SC=SC_WOND -o VP=17 results in vp overridden
2/ setting -o _SC_WOND=t -o SBL=t -o _SC_SANY=t -o VP=17 results in no scenario set, not wonders map, although wonders feature is enabled).

am i doing something wrong?

**Comment by jdmonin** [comment] 2021-04-11 15:20
Hi,

When the scenario feature was being planned, the idea was that any options specified in the scenario's `scOpts` override any other options in the game, except VP if specified, because the scenario author knows best what options they need.

The bug you see in example "1" is that although the server tells the client there's a default VP=t17, the NewGameOptionsFrame is using VP=t10 specified in the SC_WOND scenario.

If you start the server with -o VP=t17 but no scenario, NewGameOptionsFrame does use 11 as default VP.

What example "2" runs into is: The options starting with `'_'` are internal, they shouldn't be set by default or requested by clients, so it's not surprising that behavior is inconsistent. They're meant to be set only when a game is created at the server (with a scenario or otherwise).

The bugfix for victory points would most likely need to happen in NewGameOptionsFrame, or possibly in SOCGameOptionSet.getAllKnownOptions at optSC.addChangeListener .

**Comment by jdmonin** [comment] 2021-04-11 15:21
Hi,

You've found an interesting behavior :)

When the scenario feature was being planned, the idea was that any options specified in the scenario's `scOpts` override any other options in the game, except VP if specified, because the scenario author knows best what options they need.

The bug you see in example "1" is that although the server tells the client there's a default VP=t17, the NewGameOptionsFrame is using VP=t10 specified in the SC_WOND scenario.

If you start the server with -o VP=t17 but no scenario, NewGameOptionsFrame does use 17 as default VP.

What example "2" runs into is: The options starting with `'_'` are internal, they shouldn't be set by default or requested by clients, so it's not surprising that behavior is inconsistent. They're meant to be set only when a game is created at the server (with a scenario or otherwise).

The bugfix for victory points would most likely need to happen in NewGameOptionsFrame, or possibly in SOCGameOptionSet.getAllKnownOptions at optSC.addChangeListener .

**Comment by jdmonin** [comment] 2021-12-21 14:08
The upcoming v2.5 release's client will use default VP as a minimum when scenario has lower VP. Thanks for asking about this!

**Comment by kotc** [comment] 2021-12-21 15:53
nice :) while you are at it, can you make that cmd line option override any automatic vp setting function? ie. if i set it to 17 no other function would touch it (apart from user manual vp setting in game create options)

**Comment by jdmonin** [comment] 2021-12-22 04:40
Thanks :)

So, the intended behavior I've planned right now is:

- Start server with `-o VP=...` to set default VP for its games
- If user/client overrides by using the VP dropdown and checkbox, game will have VP amount from override
- Otherwise:
    - If no scenario, use server's default VP
    - If scenario specifies VP but is < default VP, game will have default VP
    - If scenario specifies VP > default, game will have scenario's VP

Are you asking for a way to make sure each game's VP is always the default, even if the scenario specifies more, unless the user overrides it?

**Comment by kotc** [comment] 2021-12-22 06:37
first two points yes, for third, if user doesnt change default vp in any way (cmd line or dropdown), then let scenario set the vp (ie. it doesnt matter if scenario vp < or > than default vp). when i play with gf we almost always use 17vp, its a setting that ensures you will have to use all the resources to win, there are draws sometimes, but that's ok too

**Comment by kotc** [comment] 2021-12-22 06:38
idea: additional message could show (but not a popup) that will suggest what is the default vp for particular scenario, or just add it to selection list names

**Comment by jdmonin** [comment] 2021-12-22 10:51
OK thanks, I think we're most of the way there with the upcoming v2.5 release.

- Right now (v2.0 - 2.4) the scenario sets the VP unless changed in the VP dropdown (New Shores has 13, Fog Islands 12, Wonders 10, etc)
- Right now the New Game dialog's VP setting is updated when a scenario is picked, unless the user has changed the VP in the VP dropdown. You can also click "Scenario Info" to show the winning VP
- In v2.5 when changing default on the server command line, game's VP will be whichever is higher: scenario VP, server default VP
- In v2.5 the New Game dialog will use that same maximum rule: Fog Islands is 12 but if server command line default is 13, then Fog Islands will use 13 unless user has changed the VP in the dropdown

If you're asking for a way to have the default VP always override scenario (Cloth Trade would be 13 instead of 14), I could add that. Although the highest scenario VP is 14, so if your command line is 14 VP or higher, it'll already do that in v2.5.

I like the idea of adding VP to the selection list names, thanks! Since v2.5 is so close to release, that would go into the next version after v2.5.

Does that sound good? Do you want a flag to always override the scenario, or would you be specifying >= 14 so it's alright without that flag? If I'm misunderstanding, just let me know :)

If no flag is needed, the current v2.5 client dialog code is all set, and I just need to finish a commit for the server side. I could also add the flag for v2.5.

**Comment by kotc** [comment] 2021-12-22 14:18
since we are usually playing to 17 it would be ok, but if we ever start liking shorter games it would be nice if vp stuck to particular value. hmm, maybe a checkbox/cmdline option to disallow scenario changing the vp?

**Comment by jdmonin** [comment] 2021-12-23 02:36
That checkbox/option sounds good to me too, yeah

**Comment by jdmonin** [comment] 2021-12-24 04:52
Working on an implementation that'll add a boolean gameopt to use default VP for all scenarios. Should have something in a day or 3 :)

**Comment by jdmonin** [comment] 2021-12-28 02:25
So if you have time and want to try this out:

- Server: https://nand.net/jsettlers/beta/js2500beta-20211223-server.jar
- Client:  https://nand.net/jsettlers/beta/js2500beta-20211223.jar
- When you start the server, include `-o VP=t17 -o _VP_ALL=t` on command line (or some other default VP > 10)
- New client's New Game dialog will recognize that all scenarios should use the default
- Current client (v2.4 or earlier) won't; you'll have to uncheck the VP checkbox after selecting a scenario, so the server will use the higher default

Let me know if that fits what you're looking for. Thanks!

**Comment by jdmonin** [comment] 2021-12-31 23:38
This was released as part of v2.5.00. We can iterate it a little afterwards if needed. :)

**Comment by kotc** [comment] 2022-01-25 15:08
works well with server started separately, now it would be nice if client would offer the last selected VPs when creating new game after last one ended :)

**Comment by jdmonin** [comment] 2022-01-28 04:40
Glad to hear :)  Yeah, the New Game dialog still has some odd behavior with VPs sometimes. Definitely room for improvment there

**Closed** 2022-01-28 04:41 UTC
Labels: bug
